apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consul-3
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
        member: consul-3
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: consul
          image: "consul:0.7.1"
          args:
            - "agent"
            - "-ui"
            - "-data-dir=/var/lib/consul"
            - "-server"
            - "-bootstrap-expect=3"
            #- "-bind=0.0.0.0"
            - "-advertise=$(CONSUL_3_SERVICE_HOST)"
            - "-client=0.0.0.0"
            - "-retry-join=$(CONSUL_1_SERVICE_HOST)"
          volumeMounts:
            - mountPath: /var/lib/consul
              name: data
          ports:
          - containerPort: 8500
            name: ui-port
          - containerPort: 8400
            name: alt-port
          - containerPort: 53
            name: udp-port
          - containerPort: 443
            name: https-port
          - containerPort: 8080
            name: http-port
          - containerPort: 8301
            name: serflan
          - containerPort: 8302
            name: serfwan
          - containerPort: 8600
            name: consuldns
          - containerPort: 8300
            name: server
          readinessProbe:
            exec:
              # Check to see if /var/lib/consul got mounted
              command:
              - grep
              - /var/lib/consul
              - /proc/mounts
            initialDelaySeconds: 10
            timeoutSeconds: 1

      volumes:
        - name: data
          gcePersistentDisk:
            pdName: consul-3
            fsType: ext4
