# Deployment for vault instance 2
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vault-2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vault
        instance: vault-2
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: vault
          image: "randyfay/vault:0.0.8"
          ports:
          - containerPort: 8200
            name: main-port
          - containerPort: 8201
            name: local-talk-port

          env:
          - name: VAULT_LOCAL_CONFIG
            # Disable registration as we don't even use consul's service discovery features
            value:
                backend "consul" {
                  address = "$(CONSUL_HTTP_SERVICE_HOST):$(CONSUL_HTTP_SERVICE_PORT)"
                  cluster_addr = "https://$(VAULT_2_SERVICE_HOST):$(VAULT_2_SERVICE_PORT_BACKENDPORT)"
                  disable_registration = 1
                }
                listener "tcp" {
                  address = "0.0.0.0:8200"
                  tls_disable = 1
                }
                disable_mlock = true
          # VAULT_ADDR is provided only for convenience - so don't have to set when logging in.
          - name: VAULT_ADDR
            value: http://localhost:8200
          readinessProbe:
            httpGet:
              path: /v1/sys/health
              port: 8200
            initialDelaySeconds: 30
            timeoutSeconds: 1
---
